### ISSUE TITLE
.summarize Returning Array Instead Of summary

### ISSUE THREAD

**Issue by dillon-co** [deepfryed/ots#7]
When I call the `.summarize` method on a parsed object it gives me an array of hashes that looks like this `[{:sentence => "some string", :score => 12}, {:sentence => 'some other string", :score => 11}]`

I had to manually join all the sentences using a method like this
 `parsed_summary.map { |h| h[:sentence] }.join("")`

I got it working but it would be nice if I didn't have to manually do this every time I wanted to create a summary

Thanks!

**Comment by deepfryed** [comment]
It's meant to reflect the libots api and return the sentences with scores for further processing. Deliberate design decision.

**Comment by deepfryed** [comment]
@grandmasterspoc you can reopen the class and add a helper method if you want to do that. It should be a couple of extra lines once off.
